name: Build with conan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.build_type }} Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Release, Debug]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Conan
        uses: conan-io/setup-conan@v1

      # following https://docs.conan.io/2/devops/devops_local_recipes_index.html#building-binaries-from-a-private-conan-center-index-fork
      - name: Setup
        run: |
          conan config install ./.config/global.conf
          conan remote remove conancenter
          conan remote add oc https://artifactory.owncloud-demo.com/artifactory/api/conan/conan-local
          conan remote login oc ${{ secrets.CONAN_USER }} -p ${{ secrets.CONAN_PASSWORD }}
          conan remote add local .
          conan remote list
          conan profile show

      - name: Disk Space Before
        run: |
          df -h

      - name: Clean Disk
        if: runner.os == 'Linux'
        run: |
          echo "Before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/lib/android
          echo "After cleanup:"
          df -h

      - name: Build
        run: |
          conan remove "*" -c
          conan install . -s build_type=${{ matrix.build_type }} --build=missing --settings "compiler.cppstd=17"

      - name: Disk Space After
        run: |
          df -h

      - name: Upload
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          conan upload -r oc "*" -c
