name: Build with conan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Conan
        uses: conan-io/setup-conan@v1

      - name: Setup
        env:
          CONAN_USER: ${{ secrets.CONAN_USER }}
          CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
        run: |
          conan remote remove conancenter
          conan remote add oc https://artifactory.owncloud-demo.com/artifactory/api/conan/conan-local
          # TODO: Windows env var handling
          conan remote login oc $CONAN_USER -p $CONAN_PASSWORD
          conan profile show

      - name: Build
        run: |
          conan create recipes/extra-cmake-modules/all/ -r oc -b missing --version=6.2.0
          conan create recipes/zlib/all/ -r oc -b missing --version=1.3.1
          conan create recipes/openssl/3.x.x/ -r oc -b missing --version=3.4.1

      - name: Upload
        #if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          conan upload -r oc *
